apiVersion: v1
data:
  cniops.cni-manager.netop-manager.io.yaml: |
    "name:unmanaged, ns:netop-manager-system, status:{\"observedGeneration\":6,\"operatorStatus\":\"Unknown\"}"
kind: ConfigMap
metadata:
  labels:
    netop-manager-resource: cniops.cni-manager.netop-manager.io
  name: aws-vpc-cniops.cni-manager.netop-manager.io
  namespace: 
