apiVersion: v1
data:
  connectivitycheckers.nettools.debug.yaml: |
    "name:test-conn-check, ns:nettools, status:{\"results\":{\"node_to_External\":\"\",\"node_to_LB_VIP\":\"\",\"node_to_NodePort\":\"\",\"node_to_clusterIP\":\"\",\"node_to_node\":\"\",\"node_to_pod\":\"\",\"pod_to_External\":\"Pass\",\"pod_to_LB_VIP\":\"Fail\",\"pod_to_NodePort\":\"Fail\",\"pod_to_clusterIP\":\"Pass\",\"pod_to_node\":\"Pass\",\"pod_to_pod\":\"Pass\",\"pod_to_service\":\"Pass\"},\"updated_at\":\"2022-05-30 12:25:49.930189269 +0000 UTC\"}"
kind: ConfigMap
metadata:
  labels:
    netop-manager-resource: connectivitycheckers.nettools.debug
  name: fab14c1-connectivitycheckers.nettools.debug
  namespace: 
