apiVersion: v1
data:
  fabricinfras.netop.mgr.yaml: |
    "name:fabric14, ns:netop-manager, status:{\"allocated\":[{\"extern_dynamic_pools\":[\"10.4.112.1/21\"],\"machine_group_profile\":\"k8s-1.21\",\"mcast_subnet_pools\":[\"225.114.1.0/16\"],\"node_subnet_pools\":[\"1.100.101.1/24\"],\"service_vlan_pools\":[102]}],\"argo_app\":\"kubectl apply -f https://raw.githubusercontent.com/networkoperator/demo-cluster-manifests/sumit-test-1/fabric-manager/argo/fabric14/argo_app.yaml\"}"
kind: ConfigMap
metadata:
  labels:
    netop-manager: fabricinfras.netop.mgr
  name: fabricinfras.netop.mgr
  namespace: netop-manager
